services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 8080:8080
    environment:
      - 'ENABLE_OPENAI_API=True'
      - 'ENABLE_OLLAMA_API=False'
      - 'OPENAI_API_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'OPENAI_API_CONFIGS={"0":{"enable":true,"prefix_id":"","model_ids":["deepseek-r1","deepseek-v3"]}}'
    restart: unless-stopped
volumes:
  open-webui: {}
