RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/deepseek-bailian
DockerComposeEnvPath: .env.example
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: String
  AllowedPattern: ''
  Label: DashScopeApiKey
  ConstraintDescription: ''
  Name: OPENAI_API_KEY
DockerComposeYamlPath: docker-compose.yaml
Owner: Alicloud-ComputeNest
Branch: main
Platform: github
